# Generated by Django 2.0.2 on 2018-10-25 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('create_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '软件管理',
                'verbose_name_plural': '软件管理',
            },
        ),
    ]
