# Generated by Django 2.0.2 on 2018-10-26 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkversion',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
